---
title: "Untitled"
output: html_document
date: "2025-01-08"
---

```{r setup, include=FALSE}
library(mixOmics)

hmp_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\hmp_data_lf.csv")
karl_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\karl_data_lf.csv")
lij_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\lij_data_lf.csv")
yuj_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\yuj_data_lf.csv")
feng_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\feng_data_lf.csv")
sank_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\sank_data_lf.csv")

lij_data_t1d = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\T1D\\lij_data.csv")
hei_data_t1d = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\T1D\\hei_data.csv")
kos_data_t1d = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\T1D\\kos_data.csv")

val = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\HGMA_data\\BioProject_PRJEB1786.csv")
data = sank_data
```

```{r}
names(data) = tolower(names(data))
names(val) = tolower(names(val))
commoncols = intersect(names(data), names(val))
data = data[, commoncols, drop = F]
val = val[, commoncols, drop = F]
```

## PCA
```{r}
pca_results = pca(X = subset(data, select = -c(disease, study)), logratio = 'none', ncomp = 2, scale = TRUE)
cust_color = c('blue', 'orange')
plotIndiv(pca_results, group = data$disease, title = "PCA", legend = T, col.per.group = cust_color, ellipse = TRUE, pch = 15)
```

## modeling
```{r cars}
plsda_results = plsda(X = subset(data, select = -c(study, disease)), Y = data$disease, ncomp = 2)
cust_color = c('blue', 'orange')
plotIndiv(plsda_results, group = data$disease, title = "PLSDA", legend = T, col.per.group = cust_color, ellipse = TRUE, pch = 15)
```

## Including Plots
```{r pressure, echo=FALSE}
perf_plsda = perf(plsda_results, validation = "Mfold", folds = 10, nrepeat = 1)
print(perf_plsda$error.rate.class)

```

```{r}
ab.splsda.tuning = tune(method = "splsda", X = subset(data, select = -c(disease)), Y = data$disease, ncomp = 5, test.keepX = seq(1, ncol(subset(data, select = -c(disease))), 1), dist = "centroids.dist", nrepeat = 1)
plot(ab.splsda.tuning)

```

```{r}
optimal.ncomp = 2
optimal.keepx = ab.splsda.tuning$choice.keepX[1:optimal.ncomp]
optimal.keepx
```

```{r}
final.splsda.model = splsda(X = subset(data, select = -c(disease)), Y = data$disease, keepX = optimal.keepx)
# final.splsda.model = splsda(X = subset(data, select = -c(disease)), Y = data$disease, keepX = c(7, 25))
plotIndiv(final.splsda.model, legend = TRUE, title = ' ', substitle = 'Global', ellipse = T)
```
```{r}
plotLoadings(final.splsda.model, contrib = "max", method = "median", comp = 1, ndisplay = 20)
plotLoadings(final.splsda.model, contrib = "max", method = "median", comp = 2, ndisplay = 20)
```

```{r}
auroc(final.splsda.model, roc.comp = 1, print = FALSE)
auroc(final.splsda.model, roc.comp = 2, print = FALSE)
```
### look at the training set performance
```{r}
predict.splsda.train <- predict(final.splsda.model, newdata = subset(data, select = -c(disease)), 
                             dist = "centroids.dist")

conf_mat_c1 = get.confusion_matrix(truth = data$disease, predicted = predict.splsda.train$class$centroids.dist[, 1])
conf_mat_c2 = get.confusion_matrix(truth = data$disease, predicted = predict.splsda.train$class$centroids.dist[, 2])
conf_mat_c1
conf_mat_c2
```


## testing
```{r}
x.test = subset(val, select = -c(disease))
y.test = val$disease
# study.test = val$study

predict.splsda <- predict(final.splsda.model, newdata = x.test, 
                             dist = "centroids.dist")

conf_mat_c1 = get.confusion_matrix(truth = y.test, predicted = predict.splsda$class$centroids.dist[, 1])
conf_mat_c2 = get.confusion_matrix(truth = y.test, predicted = predict.splsda$class$centroids.dist[, 2])
conf_mat_c1
conf_mat_c2
```

```{r}



```




