---
title: "no_sparse_case"
output: html_document
date: "2025-05-03"
---

```{r setup, include=FALSE}
library(mixOmics)
library(dplyr)
feng_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\feng_data_lf.csv")
hmp_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\hmp_data_lf.csv")
karl_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\karl_data_lf.csv")
lij_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\lij_data_lf.csv")
sank_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\sank_data_lf.csv")
yuj_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\yuj_data_lf.csv")
qin_data = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\qin_data_lfv1.csv")

# T1D
lij_data_t1d = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\T1D\\lij_data_lf.csv")
hei_data_t1d = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\T1D\\hei_data_lf.csv")
kos_data_t1d = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\curated_metagenomics\\single_study\\T1D\\kos_data_lf.csv")

## _v1 means 0.01% threshold
val = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\HGMA_data\\BioProject_PRJEB1786_v1.csv")
# val = qin_data
# val = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\HGMA_data\\BioProject_PRJNA422434_V1.csv")
# val = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\HGMA_data\\BioProject_PRJNA289586(T1D)_v1.csv")
# val = read.csv("C:\\Users\\edwar\\Desktop\\Melbourne\\research_project\\other_valsets\\Naguyen\\Naguyen.csv")
# df = bind_rows(hmp_data, feng_data, yuj_data, karl_data, lij_data)
df = bind_rows(hmp_data, feng_data, lij_data, karl_data, yuj_data)
```

# modelling the training set
```{r}
X = subset(df, select = -c(disease, study))
Y = df$disease
study = factor(df$study)

final.plsda.model = mint.plsda(X = X, Y = Y, study = study, ncomp = 2)
# plotIndiv(final.splsda.model, legend = TRUE)
mint_perf = perf(final.plsda.model)

print(mint_perf$global.error$BER)
print(mint_perf$global.error$error.rate.class)


plotIndiv(final.plsda.model, group = df$disease, pch = as.numeric(factor(df$study))+13,
          pch.levels = df$study, title = 'MINT plsda', legend = TRUE, 
          legend.title = 'disease', legend.title.pch = 'study', ellipse = T)

```

## training set performance
```{r}

predict.plsda <- predict(final.plsda.model, newdata = X, 
                             dist = "centroids.dist", study.test = study)

conf_mat_c1 = get.confusion_matrix(truth = Y, predicted = predict.plsda$class$centroids.dist[, 1])
conf_mat_c2 = get.confusion_matrix(truth = Y, predicted = predict.plsda$class$centroids.dist[, 2])
conf_mat_c1
conf_mat_c2
```



## overlapped between testing set
```{r cars}
# df = bind_rows(karl_data, hmp_data, sank_data)
val['study'] = 'hgma'
names(df) = tolower(names(df))
names(val) = tolower(names(val))
commoncols = intersect(names(df), names(val))
# commoncols = c(commoncols, 'study')
df = df[, commoncols, drop = F]
val = val[, commoncols, drop = F]

```



## model building
```{r pressure, echo=FALSE}
X = subset(df, select = -c(disease, study))
Y = df$disease
study = factor(df$study)

final.plsda.model = mint.plsda(X = X, Y = Y, study = study, ncomp = 2)
# plotIndiv(final.splsda.model, legend = TRUE)
mint_perf = perf(final.plsda.model)

print(mint_perf$global.error$BER)
print(mint_perf$global.error$error.rate.class)


plotIndiv(final.plsda.model, group = df$disease, pch = as.numeric(factor(df$study))+13,
          pch.levels = df$study, title = 'MINT plsda', legend = TRUE, 
          legend.title = 'disease', legend.title.pch = 'study', ellipse = T)

```

## testing set
```{r}
x.test = subset(val, select = -c(disease, study))
y.test = val$disease
study.test = val$study

predict.splsda <- predict(final.plsda.model, newdata = x.test, 
                             dist = "centroids.dist", study.test = study.test)

conf_mat_c1 = get.confusion_matrix(truth = y.test, predicted = predict.splsda$class$centroids.dist[, 1])
conf_mat_c2 = get.confusion_matrix(truth = y.test, predicted = predict.splsda$class$centroids.dist[, 2])
conf_mat_c1
conf_mat_c2
```








